#!/bin/bash
argc=$#
argv=("$@")
result=""
LINE_REGEXP="^[-+]?[0-9]+\.?[0-9]*:[-+]?[0-9]+\.?[0-9]*\s*$"
TRAILING_ZEROS_REMOVAL="sed -E 's/(\.[0-9])0$/\1/' | sed -E 's/\.0$//' | sed -E 's/^-0$/0/'"

function printHelp(){
    echo "..."
    echo "@~> Linear Least Squares Solver <~@"
    echo "usage: regr [ -h or --help ] You are here"
    echo "            [ -t or --test ] Run all test .txt files in ./testFiles folder"
    echo "            [ {pathToFile} ] One or more files with lines formatted as \"num1:num2\" "
    echo "e.g.:"
    echo "{ ./regr inputFile1 inputFile2 inputFile3 }"
}

function printHelpIfInvoked(){
    for (( j=0; j<argc; j++ )); do
        arg=${argv[j]}
        if [ "$arg" == "--help" ] || [ "$arg" == "-h" ]; then
            printHelp
            exit
        fi 
    done
}

function runTest(){
    runTestCommand="./regr $(find ./testFiles -name '*.txt' | tr '\n' ' ')"
    eval $runTestCommand
}

function runTestIfInvoked(){
    for (( j=0; j<argc; j++ )); do
        arg=${argv[j]}
        if [ "$arg" == "--test" ] || [ "$arg" == "-t" ]; then
            runTest
            exit
        fi 
    done
}

function calculateParameters(){
    length=$(wc -l < $tmpFile)
    sum_x=$(awk -F ':' '{s+=$1} END {print s}' $tmpFile)
    sum_y=$(awk -F ':' '{s+=$2} END {print s}' $tmpFile)
    sum_x2=$(awk -F ':' '{s+=$1^2} END {print s}' $tmpFile)
    sum_xy=$(awk -F ':' '{s+=$1*$2} END {print s}' $tmpFile)
    alpha=$(awk -v vecLength="$length" -v sum_xy="$sum_xy" -v sum_x="$sum_x" -v sum_y="$sum_y" -v sum_x2="$sum_x2" \
        'BEGIN {s=(vecLength * sum_xy - sum_x * sum_y) / (vecLength * sum_x2 - sum_x * sum_x); print s}')
    beta=$(awk -v alpha="$alpha" -v vecLength="$length" -v sum_x="$sum_x" -v sum_y="$sum_y" \
        'BEGIN {s=(sum_y - alpha * sum_x) / vecLength; print s}')
    err=$(awk -v alpha="$alpha" -v beta="$beta" -F ':' '{s+=($2-(alpha*$1+beta))^2} END {printf "%.2f", s;}' $tmpFile)
    alpha=$(printf "%.2f" $alpha | eval $TRAILING_ZEROS_REMOVAL )
    beta=$(printf "%.2f" $beta | eval $TRAILING_ZEROS_REMOVAL )
    err=$(echo $err | eval $TRAILING_ZEROS_REMOVAL )
    result="${result}FILE: $file, a=$alpha b=$beta c=1 err=$err\n"
}

function normalizeFile(){
    echo "" >> $tmpFile
    sed '/^$/d' $tmpFile > ${tmpFile}.bup
    cp ${tmpFile}.bup $tmpFile
    rm ${tmpFile}.bup
}

function parseInputFiles(){
    for (( j=0; j<argc; j++ )); do
        file=${argv[j]}
        
        if ! ([ -f "$file" ] && [ -s "$file" ]) ; then
            result="${result}FILE: $file, missing or empty file\n"
        fi

        if [ -f "$file" ] && [ -s "$file" ] ; then
            tmpFile=tmp.txt
            cp $file $tmpFile
            normalizeFile
            if [ "$(wc -l < $tmpFile)" -lt "3" ]; then
                result="${result}FILE: $file, not enough lines - at least 3 data points needed\n"
            elif [ "$(cut -f 1 -d ':' $tmpFile | uniq | wc -l)" -eq "1" ]; then # no sort needed before uniq
                beta="$(echo "-$(cut -f 1 -d ':' $tmpFile | uniq)" | sed 's/^--/-/')"
                result="${result}FILE: $file, a=1 b=$beta c=0 err=0\n"
            elif ! [ -z "$(grep -Ev "$LINE_REGEXP" $tmpFile)" ]; then
                firstInvalidLine=$(grep -Evn "$LINE_REGEXP" $tmpFile | head -n 1)
                lineNumber=$(echo $firstInvalidLine | cut -f 1 -d ':')
                firstInvalidLine=$(grep -Ev "$LINE_REGEXP" $tmpFile | head -n 1)
                result="${result}FILE: $file, invalid line $lineNumber: \"$firstInvalidLine\" - valid line \"num1:num2\" should be matched by LINE_REGEXP=\"$LINE_REGEXP\"\n"
            else
                calculateParameters
            fi
            rm $tmpFile
        fi

    done
}

function printResult(){
    printf "$result"
}

printHelpIfInvoked
runTestIfInvoked
parseInputFiles
printResult




